### ISSUE TITLE
I18n fields: first getAttribute is empty

### ISSUE THREAD

**Issue by axelzuzek** [punkave/symfony1#16]
I have several actAs I18n definitions in my schema.yml

```
Article:
  tableName: article 
 actAs:
    I18n:
      fields: [name]
 columns:
    name: string(255)
```

in my schema.yml
the first call for those i18n attributes are always empty, it works from the second call.

```
$article = Doctrine::getTable('Article')->find(1);

$article->getName(); // first call returns ""
$article->getName(); // second call returns "foo"
$article->getName(); // and all further calls return "foo"
```
the code worked fine with symfony 1.4.20
